/* tslint:disable */
/* eslint-disable */
/**
 * WeatherApplication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfoDto
 */
export interface InfoDto {
    /**
     * 
     * @type {string}
     * @memberof InfoDto
     */
    version?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InfoDto
     */
    lastLoadTime?: Date;
}

export function InfoDtoFromJSON(json: any): InfoDto {
    return InfoDtoFromJSONTyped(json, false);
}

export function InfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'lastLoadTime': !exists(json, 'lastLoadTime') ? undefined : (new Date(json['lastLoadTime'])),
    };
}

export function InfoDtoToJSON(value?: InfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'lastLoadTime': value.lastLoadTime === undefined ? undefined : (value.lastLoadTime.toISOString()),
    };
}


