/* tslint:disable */
/* eslint-disable */
/**
 * WeatherApplication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InfoDto,
    InfoDtoFromJSON,
    InfoDtoToJSON,
} from '../models';

export interface ApiInformationIdGetRequest {
    id: number;
}

/**
 * 
 */
export class InformationApi extends runtime.BaseAPI {

    /**
     */
    async apiInformationGetRaw(): Promise<runtime.ApiResponse<Array<InfoDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Information`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InfoDtoFromJSON));
    }

    /**
     */
    async apiInformationGet(): Promise<Array<InfoDto>> {
        const response = await this.apiInformationGetRaw();
        return await response.value();
    }

    /**
     */
    async apiInformationIdGetRaw(requestParameters: ApiInformationIdGetRequest): Promise<runtime.ApiResponse<InfoDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiInformationIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Information/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InfoDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiInformationIdGet(requestParameters: ApiInformationIdGetRequest): Promise<InfoDto> {
        const response = await this.apiInformationIdGetRaw(requestParameters);
        return await response.value();
    }

}
